# Generated by Django 4.0.2 on 2022-03-12 14:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choice_question_respondent_multiplechoicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='random_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privateqnaireid',
            name='id',
            field=models.CharField(default=api.models.generate_qnaire_private_id, max_length=32, primary_key=True, serialize=False),
        ),
    ]
